### PR TITLE
major rework

### PR DESCRIPTION
**Pull request by pbiering**
- replace call of external commands and tmpfile for retrieving log lines by internal read+reguar expression
- replace static line count filter by age option
- add limit option
- add logfile option
- add dryrun option
- add debug option
- improve catching error in case fail2ban is not responsive
- cosmetics

### CODE REVIEW

**Comment by WKnak** [comment]
Thanks! seems a lot of good stuff in there! I will review the work and run in my test server ASAP. Thanks in advance!

**Comment by pbiering** [comment]
when merged, I will work on enabling for IPv6 in a new PR

**Comment by pbiering** [comment]
@WKnak : applied some cosmetic fixes on top and extend debug log

**Comment by WKnak** [comment]
I will need to review some print() messages, because it is using the new 3.6 syntax. At least one of my servers we have Python 2.7. I will try to see if changing just the print syntax is enough without breaking anything else.

**Comment by jaccol** [comment]
I tried getting it to work on python 3.6 (RHEL8) that took some work. There are some modules that work differently across the python versions.
I did not want to complain about it, as python 3.6 is deprecated ...
https://devguide.python.org/versions/

If you are still on 2.7, I guess that is RHEL7 or similar. You are aware that the EOL date of RHEL7 is 2024-06-30 ?

**Comment by pbiering** [comment]
EL8 with default python 3.6 or EL7 with python 3.6 (from EPEL) -> issue replicated

```
./fail2ban-block-ip-range.py -f fail2ban.log 
Traceback (most recent call last):
  File "./fail2ban-block-ip-range.py", line 101, in <module>
    dt = datetime.fromisoformat(m.group(1))
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

EL8: simple workaround: install python38 from "appstream" and apply 

```
-- a/fail2ban-block-ip-range.py
+++ b/fail2ban-block-ip-range.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python3
+#!/usr/bin/python3.8
 #
 # Scan fail2ban log and aggregate single banned IPv4 addresses into banned networks
 #
```

EL7: no python version > 3.6 is available :-(

=> somehow the "fromisoformat" function must be replaced by something more compatible, will investigate how to do next days...if not someone else is faster....


Using EL7 + Python 2.7 causes also other problem:

```
./fail2ban-block-ip-range.py -f fail2ban.log 
  File "./fail2ban-block-ip-range.py", line 55
    print(f"Filter entries older {max_age} = {max_age_seconds}s")
                                                               ^
SyntaxError: invalid syntax
```

=> but this kind of format printing was already used in original version which was already using Python 3.

Question: as Python 3.6 on EL7 is only provided via EPEL and effectivly out-of-support, should the code changed to be also compatible for Python 2.7? If so, can one support?


> You are aware that the EOL date of RHEL7 is 2024-06-30 ?

That's only true for public clones, RHEL7 has EOSL 2028-06-30 if one buys ELS add-on subscription:
https://www.redhat.com/en/blog/announcing-4-years-extended-life-cycle-support-els-red-hat-enterprise-linux-7

**Comment by pbiering** [comment]
Fallback for Python 3 < 3.7.0 implemented with https://github.com/WKnak/fail2ban-block-ip-range/pull/11/commits/6c93209fd90213e6293fb212ec6d3cde0e3014b4
